abstract final class RouteNames {
  static const splash = 'splash';
  static const onboarding = 'onboarding';
  static const languageSelection = 'languageSelection';
  static const login = 'login';
  static const forgotPassword = 'forgotPassword';
  static const resetPassword = 'resetPassword';
  static const home = 'home';
  static const resorts = 'resorts';
  static const offers = 'offers';
  static const activities = 'activities';
  static const featuredResorts = 'featuredResorts';
  static const popularResorts = 'popularResorts';
  static const latestBlogs = 'latestBlogs';
  static const travelGuides = 'travelGuides';
  static const searchHolidays = 'searchHolidays';
  static const recentSearches = 'recentSearches';
  static const search = 'search';
  static const filters = 'filters';
  static const myTrips = 'myTrips';
  static const wishlist = 'wishlist';
  static const enquiries = 'enquiries';
  static const profile = 'profile';
}
